import type { DistrictProfile, NerState } from './types';

export const NER_STATES: NerState[] = [
  'Assam',
  'Meghalaya',
  'Arunachal Pradesh',
  'Nagaland',
  'Manipur',
  'Mizoram',
  'Tripura',
  'Sikkim',
];

export const NER_DISTRICTS: DistrictProfile[] = [
  // ASSAM (4 high-risk districts)
  {
    id: 'as_dima_hasao',
    name: 'Dima Hasao (Haflong)',
    nameHi: 'दीमा हसाओ (हाफलोंग)',
    nameAs: 'ডিমা হাছাও (হাফলং)',
    nameBn: 'ডিমা হাসাও (হাফলং)',
    nameMni: 'ꯗꯤꯃꯥ ꯍꯁꯥꯑꯣ',
    nameLus: 'Dima Hasao',
    nameKha: 'Dima Hasao',
    nameNe: 'डिमा हसाओ',
    state: 'Assam',
    lat: 25.1834,
    lon: 93.0232,
    elevationM: 950,
    averageSlopeDeg: 34,
    geologyType: 'Tertiary Shale & Sandstone',
    historicalEventCount: 38,
    population: 214102,
    deocContact: '03673-236324',
  },
  {
    id: 'as_karbi_anglong',
    name: 'Karbi Anglong (Diphu)',
    nameHi: 'कार्बी आंगलोंग (डिफू)',
    nameAs: 'কাৰ্বি আংলং (ডিফু)',
    nameBn: 'কার্বি আংলং (ডিফু)',
    nameMni: 'ꯀꯥꯔꯕꯤ ꯑꯥꯡꯂꯣꯡ',
    nameLus: 'Karbi Anglong',
    nameKha: 'Karbi Anglong',
    nameNe: 'कार्बी आंग्लोङ',
    state: 'Assam',
    lat: 26.1158,
    lon: 93.4243,
    elevationM: 680,
    averageSlopeDeg: 28,
    geologyType: 'Precambrian Metamorphics & Sedimentary',
    historicalEventCount: 19,
    population: 956313,
    deocContact: '03671-272555',
  },
  {
    id: 'as_kamrup_metro',
    name: 'Kamrup Metro (Guwahati)',
    nameHi: 'कामरूप मेट्रो (गुवाहाटी)',
    nameAs: 'কামৰূপ মহানগৰ (গুৱাহাটী)',
    nameBn: 'কামরূপ মেট্রো (গুয়াহাটি)',
    nameMni: 'ꯀꯥꯃꯔꯨꯞ ꯃꯦꯠꯔꯣ',
    nameLus: 'Kamrup Metro',
    nameKha: 'Kamrup Metro',
    nameNe: 'कामरूप मेट्रो',
    state: 'Assam',
    lat: 26.1445,
    lon: 91.7362,
    elevationM: 120,
    averageSlopeDeg: 24,
    geologyType: 'Gneissic Complex & Residual Soil Hills',
    historicalEventCount: 29,
    population: 1253938,
    deocContact: '0361-2733052',
  },
  {
    id: 'as_cachar',
    name: 'Cachar (Silchar)',
    nameHi: 'कछार (सिलचर)',
    nameAs: 'কাছাৰ (শিলচৰ)',
    nameBn: 'কাছাড় (শিলচর)',
    nameMni: 'ꯀꯆꯥꯔ (ꯁꯤꯜꯆꯔ)',
    nameLus: 'Cachar',
    nameKha: 'Cachar',
    nameNe: 'कछार',
    state: 'Assam',
    lat: 24.8333,
    lon: 92.7789,
    elevationM: 85,
    averageSlopeDeg: 22,
    geologyType: 'Surma Group Siltstone & Clay',
    historicalEventCount: 14,
    population: 1736617,
    deocContact: '03842-245866',
  },

  // MEGHALAYA (4 high-risk districts)
  {
    id: 'ml_east_khasi_hills',
    name: 'East Khasi Hills (Shillong/Cherrapunji)',
    nameHi: 'पूर्वी खासी हिल्स (शिलांग/चेरापूंजी)',
    nameAs: 'পূব খাছি পাহাৰ (শ্বিলং)',
    nameBn: 'পূর্ব খাসি পাহাড় (শিলং)',
    nameMni: 'ꯏꯁ꯭ꯠ ꯈꯥꯁꯤ ꯍꯤꯜꯁ',
    nameLus: 'East Khasi Hills',
    nameKha: 'East Khasi Hills (Sohra/Shillong)',
    nameNe: 'पूर्वी खासी हिल्स',
    state: 'Meghalaya',
    lat: 25.5788,
    lon: 91.8933,
    elevationM: 1525,
    averageSlopeDeg: 42,
    geologyType: 'Shillong Group Quartzite & Weathered Sandstone',
    historicalEventCount: 46,
    population: 825922,
    deocContact: '0364-2225289',
  },
  {
    id: 'ml_west_khasi_hills',
    name: 'West Khasi Hills (Nongstoin)',
    nameHi: 'पश्चिमी खासी हिल्स (नोंगस्टोइन)',
    nameAs: 'পশ্চিম খাছি পাহাৰ',
    nameBn: 'পশ্চিম খাসি পাহাড়',
    nameMni: 'ꯋꯦꯁ꯭ꯠ ꯈꯥꯁꯤ ꯍꯤꯜꯁ',
    nameLus: 'West Khasi Hills',
    nameKha: 'West Khasi Hills (Nongstoin)',
    nameNe: 'पश्चिमी खासी हिल्स',
    state: 'Meghalaya',
    lat: 25.5200,
    lon: 91.2700,
    elevationM: 1409,
    averageSlopeDeg: 38,
    geologyType: 'Precambrian Granite Gneiss & Granulite',
    historicalEventCount: 22,
    population: 383461,
    deocContact: '03654-280221',
  },
  {
    id: 'ml_west_garo_hills',
    name: 'West Garo Hills (Tura)',
    nameHi: 'पश्चिमी गारो हिल्स (तुरा)',
    nameAs: 'পশ্চিম গাৰো পাহাৰ (তুৰা)',
    nameBn: 'পশ্চিম গারো পাহাড় (তুরা)',
    nameMni: 'ꯋꯦꯁ꯭ꯠ ꯒꯥꯔꯣ ꯍꯤꯜꯁ',
    nameLus: 'West Garo Hills',
    nameKha: 'West Garo Hills',
    nameNe: 'पश्चिमी गारो हिल्स',
    state: 'Meghalaya',
    lat: 25.5144,
    lon: 90.2201,
    elevationM: 650,
    averageSlopeDeg: 31,
    geologyType: 'Archaean Gneissic Complex',
    historicalEventCount: 27,
    population: 643291,
    deocContact: '03651-223835',
  },
  {
    id: 'ml_jaintia_hills',
    name: 'East Jaintia Hills (Khliehriat)',
    nameHi: 'पूर्वी जयंतिया हिल्स (खलीहरियात)',
    nameAs: 'পূব জয়ন্তীয়া পাহাৰ',
    nameBn: 'পূর্ব জয়ন্তীয়া পাহাড়',
    nameMni: 'ꯏꯁ꯭ꯠ ꯖꯩꯟꯇꯤꯌꯥ ꯍꯤꯜꯁ',
    nameLus: 'East Jaintia Hills',
    nameKha: 'East Jaintia Hills',
    nameNe: 'पूर्वी जयन्तिया हिल्स',
    state: 'Meghalaya',
    lat: 25.3500,
    lon: 92.3700,
    elevationM: 1250,
    averageSlopeDeg: 36,
    geologyType: 'Coal-bearing Sandstone & Limestone',
    historicalEventCount: 31,
    population: 122939,
    deocContact: '03655-230619',
  },

  // ARUNACHAL PRADESH (4 high-risk districts)
  {
    id: 'ar_papum_pare',
    name: 'Papum Pare (Itanagar)',
    nameHi: 'पापुम पारे (ईटानगर)',
    nameAs: 'পাপুম পাৰে (ইটানগৰ)',
    nameBn: 'পাপুম পারে (ইটানগর)',
    nameMni: 'ꯄꯥꯄꯨꯃ ꯄꯥꯔꯦ',
    nameLus: 'Papum Pare',
    nameKha: 'Papum Pare',
    nameNe: 'पापुम पारे',
    state: 'Arunachal Pradesh',
    lat: 27.0844,
    lon: 93.6053,
    elevationM: 750,
    averageSlopeDeg: 35,
    geologyType: 'Siwalik Soft Sedimentary Rock',
    historicalEventCount: 33,
    population: 176573,
    deocContact: '0360-2212395',
  },
  {
    id: 'ar_tawang',
    name: 'Tawang (High Himalayas)',
    nameHi: 'तवांग (उच्च हिमालय)',
    nameAs: 'টাৱাং (উচ্চ হিমালয়)',
    nameBn: 'তাওয়াং',
    nameMni: 'ꯇꯋꯥꯡ',
    nameLus: 'Tawang',
    nameKha: 'Tawang',
    nameNe: 'तवाङ',
    state: 'Arunachal Pradesh',
    lat: 27.5861,
    lon: 91.8653,
    elevationM: 3048,
    averageSlopeDeg: 46,
    geologyType: 'Higher Himalayan Gneiss & Mica Schist',
    historicalEventCount: 41,
    population: 49977,
    deocContact: '03794-222221',
  },
  {
    id: 'ar_west_kameng',
    name: 'West Kameng (Bomdila)',
    nameHi: 'पश्चिम कामेंग (बोमडिला)',
    nameAs: 'পশ্চিম কামেং (বমডিলা)',
    nameBn: 'পশ্চিম কামেং (বোমডিলা)',
    nameMni: 'ꯋꯦꯁ꯭ꯠ ꯀꯥꯃꯦꯡ',
    nameLus: 'West Kameng',
    nameKha: 'West Kameng',
    nameNe: 'पश्चिम कामेंग',
    state: 'Arunachal Pradesh',
    lat: 27.2644,
    lon: 92.4244,
    elevationM: 2217,
    averageSlopeDeg: 44,
    geologyType: 'Lesser Himalayan Phyllite & Dolomite',
    historicalEventCount: 37,
    population: 83947,
    deocContact: '03782-222105',
  },
  {
    id: 'ar_dibang_valley',
    name: 'Dibang Valley (Anini)',
    nameHi: 'दिबांग घाटी (अनिनी)',
    nameAs: 'দিবাং উপত্যকা',
    nameBn: 'দিবাং উপত্যকা',
    nameMni: 'ꯗꯤꯕꯥꯡ ꯚꯦꯂꯤ',
    nameLus: 'Dibang Valley',
    nameKha: 'Dibang Valley',
    nameNe: 'दिबाङ उपत्यका',
    state: 'Arunachal Pradesh',
    lat: 28.7900,
    lon: 95.9000,
    elevationM: 1968,
    averageSlopeDeg: 48,
    geologyType: 'Mishmi Metamorphic Complex (MFT Zone)',
    historicalEventCount: 29,
    population: 8004,
    deocContact: '03801-222224',
  },

  // SIKKIM (4 high-risk districts)
  {
    id: 'sk_mangan',
    name: 'Mangan (North Sikkim / Chungthang)',
    nameHi: 'मंगन (उत्तरी सिक्किम / चुंगथांग)',
    nameAs: 'মাংগান (উত্তৰ ছিকিম)',
    nameBn: 'মঙ্গন (উত্তর সিকিম)',
    nameMni: 'ꯃꯥꯡꯒꯥꯟ',
    nameLus: 'Mangan',
    nameKha: 'Mangan',
    nameNe: 'मङ्गन (उत्तर सिक्किम)',
    state: 'Sikkim',
    lat: 27.5042,
    lon: 88.5284,
    elevationM: 1615,
    averageSlopeDeg: 49,
    geologyType: 'Central Crystalline Gneiss & Daling Group',
    historicalEventCount: 52,
    population: 43709,
    deocContact: '03592-234238',
  },
  {
    id: 'sk_gangtok',
    name: 'Gangtok (East Sikkim)',
    nameHi: 'गंगटोक (पूर्वी सिक्किम)',
    nameAs: 'গেংটক (পূব ছিকিম)',
    nameBn: 'গ্যাংটক (পূর্ব সিকিম)',
    nameMni: 'ꯒꯥꯡꯇꯣꯛ',
    nameLus: 'Gangtok',
    nameKha: 'Gangtok',
    nameNe: 'गान्तोक (पूर्व सिक्किम)',
    state: 'Sikkim',
    lat: 27.3389,
    lon: 88.6065,
    elevationM: 1650,
    averageSlopeDeg: 43,
    geologyType: 'Daling Phyllite, Schist & Quartzite',
    historicalEventCount: 44,
    population: 283583,
    deocContact: '03592-284444',
  },
  {
    id: 'sk_namchi',
    name: 'Namchi (South Sikkim)',
    nameHi: 'नामची (दक्षिण सिक्किम)',
    nameAs: 'নামচি (দক্ষিণ ছিকিম)',
    nameBn: 'নামচি (দক্ষিণ সিকিম)',
    nameMni: 'ꯅꯥꯃꯆꯤ',
    nameLus: 'Namchi',
    nameKha: 'Namchi',
    nameNe: 'नाम्ची (दक्षिण सिक्किम)',
    state: 'Sikkim',
    lat: 27.1667,
    lon: 88.3500,
    elevationM: 1315,
    averageSlopeDeg: 39,
    geologyType: 'Gondwana Sandstone & Daling Phyllite',
    historicalEventCount: 30,
    population: 146850,
    deocContact: '03595-263734',
  },
  {
    id: 'sk_gyalshing',
    name: 'Gyalshing (West Sikkim)',
    nameHi: 'ग्यालशिंग (पश्चिम सिक्किम)',
    nameAs: 'গ্যালশ্বিং (পশ্চিম ছিকিম)',
    nameBn: 'গ্যালশিং (পশ্চিম সিকিম)',
    nameMni: 'ꯒ꯭ꯌꯥꯜꯁꯤꯡ',
    nameLus: 'Gyalshing',
    nameKha: 'Gyalshing',
    nameNe: 'ग्यालशिङ (पश्चिम सिक्किम)',
    state: 'Sikkim',
    lat: 27.2833,
    lon: 88.2500,
    elevationM: 2000,
    averageSlopeDeg: 45,
    geologyType: 'Daling Series & Kanchenjunga Gneiss',
    historicalEventCount: 36,
    population: 136435,
    deocContact: '03595-250763',
  },

  // NAGALAND (3 high-risk districts)
  {
    id: 'nl_kohima',
    name: 'Kohima (State Capital)',
    nameHi: 'कोहिमा (राजधानी)',
    nameAs: 'কহিমা (ৰাজধানী)',
    nameBn: 'কোহিমা (রাজধানী)',
    nameMni: 'ꯀꯣꯍꯤꯃꯥ',
    nameLus: 'Kohima',
    nameKha: 'Kohima',
    nameNe: 'कोहिमा',
    state: 'Nagaland',
    lat: 25.6751,
    lon: 94.1086,
    elevationM: 1444,
    averageSlopeDeg: 37,
    geologyType: 'Disang Group Slaty Shale & Flysch',
    historicalEventCount: 39,
    population: 267988,
    deocContact: '0370-2290028',
  },
  {
    id: 'nl_kiphire',
    name: 'Kiphire (Saramati Range)',
    nameHi: 'किफिरे (सरमती श्रेणी)',
    nameAs: 'কিফিৰে',
    nameBn: 'কিফিরে',
    nameMni: 'ꯀꯤꯐꯤꯔꯦ',
    nameLus: 'Kiphire',
    nameKha: 'Kiphire',
    nameNe: 'किफिरे',
    state: 'Nagaland',
    lat: 25.8600,
    lon: 94.7800,
    elevationM: 1600,
    averageSlopeDeg: 41,
    geologyType: 'Ophiolite Belt & Crushed Metasediments',
    historicalEventCount: 26,
    population: 74004,
    deocContact: '03863-225528',
  },
  {
    id: 'nl_wokha',
    name: 'Wokha (Doyang Choke Point)',
    nameHi: 'वोखा (डोयांग चोक पॉइंट)',
    nameAs: 'ৱোখা',
    nameBn: 'ভোখা',
    nameMni: 'ꯋꯣꯈꯥ',
    nameLus: 'Wokha',
    nameKha: 'Wokha',
    nameNe: 'वोखा',
    state: 'Nagaland',
    lat: 26.1000,
    lon: 94.2600,
    elevationM: 1313,
    averageSlopeDeg: 35,
    geologyType: 'Barail Sandstone & Disang Shale Interbeds',
    historicalEventCount: 21,
    population: 166343,
    deocContact: '03860-222340',
  },

  // MANIPUR (3 high-risk districts)
  {
    id: 'mn_noney',
    name: 'Noney (Tupul Railway Corridor)',
    nameHi: 'नोने (टुपुल रेलवे कॉरिडोर)',
    nameAs: 'ননে (টুপুল)',
    nameBn: 'নোনে (টুপুল রেলওয়ে করিডোর)',
    nameMni: 'ꯅꯣꯅꯦ (ꯇꯨꯄꯨꯜ ꯔꯦꯜꯋꯦ)',
    nameLus: 'Noney',
    nameKha: 'Noney',
    nameNe: 'नोने (टुपुल)',
    state: 'Manipur',
    lat: 24.8167,
    lon: 93.6000,
    elevationM: 780,
    averageSlopeDeg: 44,
    geologyType: 'Highly weathered Disang Shale & Colluvium',
    historicalEventCount: 35,
    population: 43500,
    deocContact: '03874-234200',
  },
  {
    id: 'mn_tamenglong',
    name: 'Tamenglong (Hill Range)',
    nameHi: 'तामेंगलोंग (पर्वतीय क्षेत्र)',
    nameAs: 'তমেংলং',
    nameBn: 'তামেংলং',
    nameMni: 'ꯇꯃꯦꯡꯂꯣꯡ',
    nameLus: 'Tamenglong',
    nameKha: 'Tamenglong',
    nameNe: 'तामेंगलोङ',
    state: 'Manipur',
    lat: 24.9850,
    lon: 93.4980,
    elevationM: 1260,
    averageSlopeDeg: 40,
    geologyType: 'Disang & Barail Formations',
    historicalEventCount: 28,
    population: 140651,
    deocContact: '03877-267210',
  },
  {
    id: 'mn_churachandpur',
    name: 'Churachandpur (Lamka)',
    nameHi: 'चुराचांदपुर (लमका)',
    nameAs: 'চুৰাচান্দপুৰ',
    nameBn: 'চূড়াচাঁদপুর',
    nameMni: 'ꯆꯨꯔꯥꯆꯥꯟꯗꯄꯨꯔ',
    nameLus: 'Churachandpur (Lamka)',
    nameKha: 'Churachandpur',
    nameNe: 'चुराचाँदपुर',
    state: 'Manipur',
    lat: 24.3333,
    lon: 93.6833,
    elevationM: 922,
    averageSlopeDeg: 33,
    geologyType: 'Disang Shale with Ophiolitic Melange',
    historicalEventCount: 18,
    population: 274143,
    deocContact: '03874-234211',
  },

  // MIZORAM (3 high-risk districts)
  {
    id: 'mz_aizawl',
    name: 'Aizawl (State Capital)',
    nameHi: 'आइजोल (राजधानी)',
    nameAs: 'আইজল (ৰাজধানী)',
    nameBn: 'আইজল (রাজধানী)',
    nameMni: 'ꯑꯥꯏꯖꯣꯜ',
    nameLus: 'Aizawl Khawpui',
    nameKha: 'Aizawl',
    nameNe: 'आइजोल',
    state: 'Mizoram',
    lat: 23.7271,
    lon: 92.7176,
    elevationM: 1132,
    averageSlopeDeg: 41,
    geologyType: 'Surma & Tipam Sandstone with Mudstone interbeds',
    historicalEventCount: 45,
    population: 400309,
    deocContact: '0389-2325350',
  },
  {
    id: 'mz_lunglei',
    name: 'Lunglei (Southern Ridge)',
    nameHi: 'लुंगलेई (दक्षिणी रिज)',
    nameAs: 'লুংলেঈ',
    nameBn: 'লুংলেই',
    nameMni: 'ꯂꯨꯡꯂꯦꯏ',
    nameLus: 'Lunglei Veng',
    nameKha: 'Lunglei',
    nameNe: 'लुङ्गलई',
    state: 'Mizoram',
    lat: 22.8800,
    lon: 92.7300,
    elevationM: 1222,
    averageSlopeDeg: 38,
    geologyType: 'Middle Bhuban Siltstone & Shale',
    historicalEventCount: 25,
    population: 161428,
    deocContact: '0372-2324034',
  },
  {
    id: 'mz_serchhip',
    name: 'Serchhip (Mat River Valley)',
    nameHi: 'सेरछिप (मात नदी घाटी)',
    nameAs: 'চেৰছিপ',
    nameBn: 'সেরছিপ',
    nameMni: 'ꯁꯦꯔꯆꯤꯞ',
    nameLus: 'Serchhip',
    nameKha: 'Serchhip',
    nameNe: 'सेरछिप',
    state: 'Mizoram',
    lat: 23.3400,
    lon: 92.8500,
    elevationM: 888,
    averageSlopeDeg: 36,
    geologyType: 'Upper Bhuban Fine Sandstone',
    historicalEventCount: 17,
    population: 64937,
    deocContact: '03838-222214',
  },

  // TRIPURA (3 high-risk districts)
  {
    id: 'tr_dhalai',
    name: 'Dhalai (Ambassa)',
    nameHi: 'धलाई (अम्बासा)',
    nameAs: 'ধলাই (আমবাছা)',
    nameBn: 'ধলাই (আমবাসা)',
    nameMni: 'ꯙꯂꯥꯏ',
    nameLus: 'Dhalai',
    nameKha: 'Dhalai',
    nameNe: 'धलाई',
    state: 'Tripura',
    lat: 23.9200,
    lon: 91.8500,
    elevationM: 180,
    averageSlopeDeg: 26,
    geologyType: 'Tipam Group Friable Sandstone',
    historicalEventCount: 16,
    population: 378230,
    deocContact: '03826-267244',
  },
  {
    id: 'tr_north_tripura',
    name: 'North Tripura (Dharmanagar)',
    nameHi: 'उत्तरी त्रिपुरा (धर्मनगर)',
    nameAs: 'উত্তৰ ত্ৰিপুৰা',
    nameBn: 'উত্তর ত্রিপুরা (ধর্মনগর)',
    nameMni: 'ꯅꯣꯔꯊ ꯇ꯭ꯔꯤꯄꯨꯔꯥ',
    nameLus: 'North Tripura',
    nameKha: 'North Tripura',
    nameNe: 'उत्तर त्रिपुरा',
    state: 'Tripura',
    lat: 24.3700,
    lon: 92.1700,
    elevationM: 95,
    averageSlopeDeg: 23,
    geologyType: 'Dupitila Unconsolidated Sands & Clays',
    historicalEventCount: 12,
    population: 417441,
    deocContact: '03822-220042',
  },
  {
    id: 'tr_unakoti',
    name: 'Unakoti (Kailashahar)',
    nameHi: 'उनाकोटी (कैलाशहर)',
    nameAs: 'উFailকোটি (কৈলাসহৰ)',
    nameBn: 'ঊনকোটি (কৈলাসহর)',
    nameMni: 'ꯎꯅꯥꯀꯣꯇꯤ',
    nameLus: 'Unakoti',
    nameKha: 'Unakoti',
    nameNe: 'उनाकोटी',
    state: 'Tripura',
    lat: 24.3300,
    lon: 92.0000,
    elevationM: 110,
    averageSlopeDeg: 25,
    geologyType: 'Bhuban Formation Sandstone Escarpment',
    historicalEventCount: 15,
    population: 276506,
    deocContact: '03824-222238',
  },
];
