import type { DistrictProfile, NerState } from './types';

export const NER_STATES: NerState[] = [
  'Assam',
  'Meghalaya',
  'Arunachal Pradesh',
  'Nagaland',
  'Manipur',
  'Mizoram',
  'Tripura',
  'Sikkim',
];

export const NER_DISTRICTS: DistrictProfile[] = [
  {
    "id": "as_dima_hasao",
    "name": "Dima Hasao (Haflong)",
    "nameHi": "दिमा हसाओ (हाफलोंग)",
    "nameAs": "ডিমা হাছাও (হাফলং)",
    "nameBn": "ডিমা হাসাও (হাফলং)",
    "nameMni": "দিমা হসাও (হাফলোং)",
    "nameLus": "Dima Hasao (Haflong)",
    "nameKha": "Dima Hasao (Haflong)",
    "nameNe": "डिमा हासाओ (हाफलोंग)",
    "state": "Assam",
    "lat": 25.1834,
    "lon": 93.0232,
    "elevationM": 950,
    "averageSlopeDeg": 34,
    "geologyType": "Tertiary Shale & Sandstone",
    "historicalEventCount": 38,
    "population": 214102,
    "deocContact": "03673-236324"
  },
  {
    "id": "as_karbi_anglong",
    "name": "Karbi Anglong (Diphu)",
    "nameHi": "कार्बी आंगलोंग (डिफू)",
    "nameAs": "কাৰ্বি আংলং (ডিফু)",
    "nameBn": "কার্বি আংলং (ডিফু)",
    "nameMni": "কার্বি আংলোং (দিফু)",
    "nameLus": "Karbi Anglong (Diphu)",
    "nameKha": "Karbi Anglong (Diphu)",
    "nameNe": "कार्बी आंगलोंग (डिफु)",
    "state": "Assam",
    "lat": 26.1158,
    "lon": 93.4243,
    "elevationM": 680,
    "averageSlopeDeg": 28,
    "geologyType": "Precambrian Metamorphics & Sedimentary",
    "historicalEventCount": 19,
    "population": 956313,
    "deocContact": "03671-272555"
  },
  {
    "id": "as_kamrup_metro",
    "name": "Kamrup Metro (Guwahati)",
    "nameHi": "कामरूप महानगर (गुवाहाटी)",
    "nameAs": "কামৰূপ মহানগৰ (গুৱাহাটী)",
    "nameBn": "কামরূপ মহানগর (গুয়াহাটি)",
    "nameMni": "কামরূপ মেত্রো (গুৱাহাটি)",
    "nameLus": "Kamrup Metro (Guwahati)",
    "nameKha": "Kamrup Metro (Guwahati)",
    "nameNe": "कामरुप महानगर (गुवाहाटी)",
    "state": "Assam",
    "lat": 26.1445,
    "lon": 91.7362,
    "elevationM": 55,
    "averageSlopeDeg": 22,
    "geologyType": "Granitic Gneiss Inselbergs in Alluvium",
    "historicalEventCount": 24,
    "population": 1253938,
    "deocContact": "0361-2733052"
  },
  {
    "id": "as_cachar",
    "name": "Cachar (Silchar)",
    "nameHi": "कछार (सिलचर)",
    "nameAs": "কাছাৰ (শিলচৰ)",
    "nameBn": "কাছাড় (শিলচর)",
    "nameMni": "কছাড় (শিলচর)",
    "nameLus": "Cachar (Silchar)",
    "nameKha": "Cachar (Silchar)",
    "nameNe": "कछार (सिलचर)",
    "state": "Assam",
    "lat": 24.8333,
    "lon": 92.7789,
    "elevationM": 22,
    "averageSlopeDeg": 18,
    "geologyType": "Surma Series Siltstone & Clay",
    "historicalEventCount": 15,
    "population": 1736617,
    "deocContact": "03842-245866"
  },
  {
    "id": "mg_east_khasi_hills",
    "name": "East Khasi Hills (Shillong/Cherrapunji)",
    "nameHi": "पूर्वी खासी हिल्स (शिलांग/चेरापूंजी)",
    "nameAs": "পূব খাছি পাহাৰ (শ্বিলং/চেৰাপুঞ্জী)",
    "nameBn": "পূর্ব খাসি পাহাড় (শিলং/চেরাপুঞ্জি)",
    "nameMni": "নোংপোক খাসি চীং (শিলং/চেরা)",
    "nameLus": "East Khasi Hills (Shillong)",
    "nameKha": "Khasi Hills Mihngi (Sohra/Shillong)",
    "nameNe": "पूर्वी खासी हिल्स (शिलोङ/चेरापुञ्जी)",
    "state": "Meghalaya",
    "lat": 25.5788,
    "lon": 91.8933,
    "elevationM": 1525,
    "averageSlopeDeg": 42,
    "geologyType": "Shillong Group Quartzite & Weathered Sandstone",
    "historicalEventCount": 52,
    "population": 825922,
    "deocContact": "0364-2225289"
  },
  {
    "id": "mg_west_khasi_hills",
    "name": "West Khasi Hills (Nongstoin)",
    "nameHi": "पश्चिमी खासी हिल्स (नोंगस्टोइन)",
    "nameAs": "পশ্চিম খাছি পাহাৰ (নংষ্টইন)",
    "nameBn": "পশ্চিম খাসি পাহাড় (নংস্টোইন)",
    "nameMni": "নোংচুপ খাসি চীং (নোংস্তোইন্)",
    "nameLus": "West Khasi Hills (Nongstoin)",
    "nameKha": "Khasi Hills Sepngi (Nongstoiñ)",
    "nameNe": "पश्चिमी खासी हिल्स (नोङस्टोइन)",
    "state": "Meghalaya",
    "lat": 25.5167,
    "lon": 91.2667,
    "elevationM": 1409,
    "averageSlopeDeg": 38,
    "geologyType": "Granite Plutons & Metasedimentary Rocks",
    "historicalEventCount": 31,
    "population": 383461,
    "deocContact": "03654-280221"
  },
  {
    "id": "mg_west_garo_hills",
    "name": "West Garo Hills (Tura)",
    "nameHi": "पश्चिमी गारो हिल्स (तुरा)",
    "nameAs": "পশ্চিম গাৰো পাহাৰ (তুৰা)",
    "nameBn": "পশ্চিম গারো পাহাড় (তুরা)",
    "nameMni": "নোংচুপ গারো চীং (তুরা)",
    "nameLus": "West Garo Hills (Tura)",
    "nameKha": "Garo Hills Sepngi (Tura)",
    "nameNe": "पश्चिमी गारो हिल्स (तुरा)",
    "state": "Meghalaya",
    "lat": 25.5144,
    "lon": 90.2023,
    "elevationM": 349,
    "averageSlopeDeg": 35,
    "geologyType": "Gneissic Complex with Laterite Cover",
    "historicalEventCount": 29,
    "population": 643291,
    "deocContact": "03651-223835"
  },
  {
    "id": "mg_east_jaintia_hills",
    "name": "East Jaintia Hills (Khliehriat)",
    "nameHi": "पूर्वी जयंतिया हिल्स (खलीहरियात)",
    "nameAs": "পূব জয়ন্তীয়া পাহাৰ (খ্লিহৰিয়াত)",
    "nameBn": "পূর্ব জয়ন্তিয়া পাহাড় (খ্লিহরিয়াত)",
    "nameMni": "নোংপোক জৈন্তিয়া চীং",
    "nameLus": "East Jaintia Hills (Khliehriat)",
    "nameKha": "Jaiñtia Hills Mihngi (Khliehriat)",
    "nameNe": "पूर्वी जयन्तिया हिल्स (खलीहरियात)",
    "state": "Meghalaya",
    "lat": 25.35,
    "lon": 92.3667,
    "elevationM": 1250,
    "averageSlopeDeg": 36,
    "geologyType": "Limestone & Coal-Bearing Sandstone Sinkholes",
    "historicalEventCount": 34,
    "population": 122936,
    "deocContact": "03655-230025"
  },
  {
    "id": "ar_papum_pare",
    "name": "Papum Pare (Itanagar)",
    "nameHi": "पपुम पारे (ईटानगर)",
    "nameAs": "পাপুম পাৰে (ইটানগৰ)",
    "nameBn": "পাপুম পারে (ইটানগর)",
    "nameMni": "পাপুম পারে (ইতানগর)",
    "nameLus": "Papum Pare (Itanagar)",
    "nameKha": "Papum Pare (Itanagar)",
    "nameNe": "पापुम पारे (ईटानगर)",
    "state": "Arunachal Pradesh",
    "lat": 27.1004,
    "lon": 93.6166,
    "elevationM": 750,
    "averageSlopeDeg": 38,
    "geologyType": "Siwalik Fragile Sandstone & Silt",
    "historicalEventCount": 36,
    "population": 176573,
    "deocContact": "0360-2212374"
  },
  {
    "id": "ar_tawang",
    "name": "Tawang (High Himalayas)",
    "nameHi": "तवांग (उच्च हिमालय)",
    "nameAs": "তাৱাং (উচ্চ হিমালয়)",
    "nameBn": "তাওয়াং (উচ্চ হিমালয়)",
    "nameMni": "তাৱাং (চীংজিং)",
    "nameLus": "Tawang (High Himalayas)",
    "nameKha": "Tawang",
    "nameNe": "तवाङ (उच्च हिमालय)",
    "state": "Arunachal Pradesh",
    "lat": 27.5861,
    "lon": 91.8594,
    "elevationM": 3048,
    "averageSlopeDeg": 46,
    "geologyType": "Higher Himalayan Crystalline Complex",
    "historicalEventCount": 44,
    "population": 49977,
    "deocContact": "03794-222222"
  },
  {
    "id": "ar_west_kameng",
    "name": "West Kameng (Bomdila)",
    "nameHi": "पश्चिम कामेंग (बोमडिला)",
    "nameAs": "পশ্চিম কামেং (বমডিলা)",
    "nameBn": "পশ্চিম কামেং (বোমডিলা)",
    "nameMni": "নোংচুপ কামেং (বোমদিলা)",
    "nameLus": "West Kameng (Bomdila)",
    "nameKha": "West Kameng (Bomdila)",
    "nameNe": "पश्चिम कामेंग (बोमडिला)",
    "state": "Arunachal Pradesh",
    "lat": 27.2645,
    "lon": 92.4159,
    "elevationM": 2217,
    "averageSlopeDeg": 44,
    "geologyType": "Lesser Himalayan Schist & Phyllite",
    "historicalEventCount": 41,
    "population": 83936,
    "deocContact": "03782-222008"
  },
  {
    "id": "ar_east_siang",
    "name": "East Siang (Pasighat)",
    "nameHi": "पूर्वी सियांग (पासीघाट)",
    "nameAs": "পূব চিয়াং (পাচীঘাট)",
    "nameBn": "পূর্ব সিয়াং (পাসিঘাট)",
    "nameMni": "নোংপোক সিয়াং (পাসিঘাট)",
    "nameLus": "East Siang (Pasighat)",
    "nameKha": "East Siang (Pasighat)",
    "nameNe": "पूर्वी सियाङ (पासीघाट)",
    "state": "Arunachal Pradesh",
    "lat": 28.0667,
    "lon": 95.3333,
    "elevationM": 153,
    "averageSlopeDeg": 32,
    "geologyType": "Sub-Himalayan Foreland Basin & Alluvium",
    "historicalEventCount": 27,
    "population": 99214,
    "deocContact": "0368-2222225"
  },
  {
    "id": "ar_dibang_valley",
    "name": "Dibang Valley (Anini)",
    "nameHi": "दिबांग घाटी (अनिनी)",
    "nameAs": "দিবাং উপত্যকা (অনিনী)",
    "nameBn": "দিবাং উপত্যকা (অনিনী)",
    "nameMni": "দিবাং তম্পাক (অনিনী)",
    "nameLus": "Dibang Valley (Anini)",
    "nameKha": "Dibang Valley (Anini)",
    "nameNe": "दिबाङ उपत्यका (अनिनी)",
    "state": "Arunachal Pradesh",
    "lat": 28.79,
    "lon": 95.9,
    "elevationM": 1968,
    "averageSlopeDeg": 48,
    "geologyType": "Mishmi Metamorphics & Fault Gaps",
    "historicalEventCount": 35,
    "population": 8004,
    "deocContact": "03801-222221"
  },
  {
    "id": "nl_kohima",
    "name": "Kohima (State Capital)",
    "nameHi": "कोहिमा (राज्य राजधानी)",
    "nameAs": "কহিমা (ৰাজ্যিক ৰাজধানী)",
    "nameBn": "কোহিমা (রাজ্য রাজধানী)",
    "nameMni": "কোহিমা (রাজ্যগী কোনুং)",
    "nameLus": "Kohima (State Capital)",
    "nameKha": "Kohima (Nongbah)",
    "nameNe": "कोहिमा (प्रदेश राजधानी)",
    "state": "Nagaland",
    "lat": 25.6701,
    "lon": 94.1077,
    "elevationM": 1444,
    "averageSlopeDeg": 37,
    "geologyType": "Disang Group Mudstone & Unstable Clay",
    "historicalEventCount": 47,
    "population": 267988,
    "deocContact": "0370-2290028"
  },
  {
    "id": "nl_mokokchung",
    "name": "Mokokchung",
    "nameHi": "मोकोकचुंग",
    "nameAs": "মোককচাং",
    "nameBn": "মোককচুং",
    "nameMni": "মোকোকচুং",
    "nameLus": "Mokokchung",
    "nameKha": "Mokokchung",
    "nameNe": "मोकोकचुङ",
    "state": "Nagaland",
    "lat": 26.3256,
    "lon": 94.5295,
    "elevationM": 1325,
    "averageSlopeDeg": 34,
    "geologyType": "Barail Group Sandstone-Shale Flysch",
    "historicalEventCount": 23,
    "population": 194622,
    "deocContact": "0369-2226222"
  },
  {
    "id": "nl_phek",
    "name": "Phek",
    "nameHi": "फेक",
    "nameAs": "ফেক",
    "nameBn": "ফেক",
    "nameMni": "ফেক",
    "nameLus": "Phek",
    "nameKha": "Phek",
    "nameNe": "फेक",
    "state": "Nagaland",
    "lat": 25.656,
    "lon": 94.498,
    "elevationM": 1524,
    "averageSlopeDeg": 39,
    "geologyType": "Ophiolite Belt & High Weathered Clay",
    "historicalEventCount": 28,
    "population": 163418,
    "deocContact": "03865-223030"
  },
  {
    "id": "nl_wokha",
    "name": "Wokha (Doyang Choke Point)",
    "nameHi": "वोखा (डोयांग चोक पॉइंट)",
    "nameAs": "ৱখা (দয়াং চক পইণ্ট)",
    "nameBn": "ওখা (দোয়াং চোক পয়েন্ট)",
    "nameMni": "ৱোখা (দোয়াং)",
    "nameLus": "Wokha (Doyang)",
    "nameKha": "Wokha (Doyang)",
    "nameNe": "वोखा (दोयाङ चोक पोइन्ट)",
    "state": "Nagaland",
    "lat": 26.1,
    "lon": 94.2667,
    "elevationM": 1313,
    "averageSlopeDeg": 36,
    "geologyType": "Disang-Barail Transition Zone",
    "historicalEventCount": 31,
    "population": 166343,
    "deocContact": "03860-222345"
  },
  {
    "id": "nl_kiphire",
    "name": "Kiphire (Saramati Range)",
    "nameHi": "किफ़िरे (सरामाती रेंज)",
    "nameAs": "কিফিৰে (চাৰামতি শৃংগ)",
    "nameBn": "কিফিরে (সারামতি রেঞ্জ)",
    "nameMni": "কিফিরে (সরামতি চীং)",
    "nameLus": "Kiphire (Saramati Range)",
    "nameKha": "Kiphire (Saramati)",
    "nameNe": "किफिर (सरामाती क्षेत्र)",
    "state": "Nagaland",
    "lat": 25.8667,
    "lon": 94.7833,
    "elevationM": 1600,
    "averageSlopeDeg": 42,
    "geologyType": "Nagaland Ophiolite Complex & Melange",
    "historicalEventCount": 33,
    "population": 74004,
    "deocContact": "03863-225210"
  },
  {
    "id": "mn_noney",
    "name": "Noney (Tupul Railway Corridor)",
    "nameHi": "नोने (टुपुल रेलवे कॉरिडोर)",
    "nameAs": "ননে (টুপুল ৰেল কৰিডৰ)",
    "nameBn": "নোনে (টুপুল রেলওয়ে করিডোর)",
    "nameMni": "নোনে (তুপুল রেলৱে কোরিদোর)",
    "nameLus": "Noney (Tupul Railway Corridor)",
    "nameKha": "Noney (Tupul)",
    "nameNe": "नोने (तुपुल रेलवे करिडोर)",
    "state": "Manipur",
    "lat": 24.81,
    "lon": 93.6,
    "elevationM": 780,
    "averageSlopeDeg": 43,
    "geologyType": "Thrust-Faulted Disang Shale & Colluvium",
    "historicalEventCount": 39,
    "population": 38290,
    "deocContact": "03874-222123"
  },
  {
    "id": "mn_kangpokpi",
    "name": "Kangpokpi (NH-2 Lifeline)",
    "nameHi": "कांगपोकपी (एनएच-2 लाइफलाइन)",
    "nameAs": "কাংপোকপী (এনএইচ-২)",
    "nameBn": "কাংপোকপী (এনএইচ-২ লাইফলাইন)",
    "nameMni": "কাংপোকপী (এন.ঐচ-২ লাইফলাইন)",
    "nameLus": "Kangpokpi (NH-2)",
    "nameKha": "Kangpokpi (NH-2)",
    "nameNe": "काङपोकपी (एनएच-२ लाइफलाइन)",
    "state": "Manipur",
    "lat": 25.15,
    "lon": 93.97,
    "elevationM": 990,
    "averageSlopeDeg": 36,
    "geologyType": "Soft Laminated Siltstone with Overburden",
    "historicalEventCount": 31,
    "population": 193744,
    "deocContact": "03871-222415"
  },
  {
    "id": "mn_tamenglong",
    "name": "Tamenglong (Hill Range)",
    "nameHi": "तामेंगलोंग (पहाड़ी क्षेत्र)",
    "nameAs": "তামেংলাং (পাহাৰীয়া অঞ্চল)",
    "nameBn": "তামেংলং (পাহাড়ী অঞ্চল)",
    "nameMni": "তামেংলোং (চীং খোং)",
    "nameLus": "Tamenglong (Hill Range)",
    "nameKha": "Tamenglong (Lum)",
    "nameNe": "तामेङलोङ (पहाडी क्षेत्र)",
    "state": "Manipur",
    "lat": 24.9833,
    "lon": 93.4833,
    "elevationM": 1260,
    "averageSlopeDeg": 41,
    "geologyType": "Barail Formation Escarpment Slopes",
    "historicalEventCount": 34,
    "population": 140651,
    "deocContact": "03877-267210"
  },
  {
    "id": "mz_aizawl",
    "name": "Aizawl (State Capital)",
    "nameHi": "आइजोल (राज्य राजधानी)",
    "nameAs": "আইজল (ৰাজ্যিক ৰাজধানী)",
    "nameBn": "আইজল (রাজ্য রাজধানী)",
    "nameMni": "আইজোল (রাজ্যগী কোনুং)",
    "nameLus": "Aizawl (Khawpui)",
    "nameKha": "Aizawl (Nongbah)",
    "nameNe": "आइजोल (प्रदेश राजधानी)",
    "state": "Mizoram",
    "lat": 23.7271,
    "lon": 92.7176,
    "elevationM": 1132,
    "averageSlopeDeg": 45,
    "geologyType": "Bhuban Formation Alternating Silt & Sand",
    "historicalEventCount": 49,
    "population": 400309,
    "deocContact": "0389-2325372"
  },
  {
    "id": "mz_lunglei",
    "name": "Lunglei",
    "nameHi": "लुंगलेई",
    "nameAs": "লুংলেই",
    "nameBn": "লুংলেই",
    "nameMni": "লুংলেই",
    "nameLus": "Lunglei (Khawpui)",
    "nameKha": "Lunglei",
    "nameNe": "लुङ्ग्लेई",
    "state": "Mizoram",
    "lat": 22.8671,
    "lon": 92.7651,
    "elevationM": 1222,
    "averageSlopeDeg": 38,
    "geologyType": "Tertiary Folded Strata & Weathered Regolith",
    "historicalEventCount": 26,
    "population": 161428,
    "deocContact": "0372-2324200"
  },
  {
    "id": "mz_champhai",
    "name": "Champhai (Indo-Myanmar Fault)",
    "nameHi": "चम्फाई (भारत-म्यांमार सीमा)",
    "nameAs": "চাম্ফাই (ভাৰত-ম্যানমাৰ সীমান্ত)",
    "nameBn": "চাম্ফাই (ভারত-মায়ানমার সীমা)",
    "nameMni": "চাম্ফাই (ভারত-মায়ানমার)",
    "nameLus": "Champhai (Ramri)",
    "nameKha": "Champhai",
    "nameNe": "चम्फाई (भारत-म्यानमार सिमाना)",
    "state": "Mizoram",
    "lat": 23.4754,
    "lon": 93.3283,
    "elevationM": 1678,
    "averageSlopeDeg": 35,
    "geologyType": "Fractured Sandstone & Tectonic Suture",
    "historicalEventCount": 21,
    "population": 125745,
    "deocContact": "03831-235222"
  },
  {
    "id": "tr_dhalai",
    "name": "Dhalai (Ambassa)",
    "nameHi": "धलाई (अम्बासा)",
    "nameAs": "ধলাই (আম্বাচা)",
    "nameBn": "ধলাই (আমবাসা)",
    "nameMni": "ধলাই (অম্বাসা)",
    "nameLus": "Dhalai (Ambassa)",
    "nameKha": "Dhalai",
    "nameNe": "धलाई (अम्बासा)",
    "state": "Tripura",
    "lat": 23.9167,
    "lon": 91.8333,
    "elevationM": 115,
    "averageSlopeDeg": 26,
    "geologyType": "Tipam Group Semi-Consolidated Sandstone",
    "historicalEventCount": 16,
    "population": 378230,
    "deocContact": "03826-267231"
  },
  {
    "id": "tr_north_tripura",
    "name": "North Tripura (Dharmanagar)",
    "nameHi": "उत्तर त्रिपुरा (धर्मनगर)",
    "nameAs": "উত্তৰ ত্ৰিপুৰা (ধৰ্মনগৰ)",
    "nameBn": "উত্তর ত্রিপুরা (ধর্মনগর)",
    "nameMni": "নোংপোক ত্রিপুরা (ধর্মনগর)",
    "nameLus": "North Tripura (Dharmanagar)",
    "nameKha": "North Tripura",
    "nameNe": "उत्तर त्रिपुरा (धर्मनगर)",
    "state": "Tripura",
    "lat": 24.3833,
    "lon": 92.1667,
    "elevationM": 88,
    "averageSlopeDeg": 24,
    "geologyType": "Dupitila Unconsolidated Clay Sand Beds",
    "historicalEventCount": 12,
    "population": 417441,
    "deocContact": "03822-220202"
  },
  {
    "id": "sk_mangan",
    "name": "Mangan (North Sikkim / Chungthang)",
    "nameHi": "मंगन (उत्तरी सिक्किम / चुंगथांग)",
    "nameAs": "মাংগন (উত্তৰ ছিকিম / চুংথাং)",
    "nameBn": "মাঙ্গান (উত্তর সিকিম / চুংথাং)",
    "nameMni": "মঙ্গান (অৱাং সিকিম)",
    "nameLus": "Mangan (North Sikkim)",
    "nameKha": "Mangan (North Sikkim)",
    "nameNe": "मङ्गन (उत्तर सिक्किम / चुङथाङ)",
    "state": "Sikkim",
    "lat": 27.5167,
    "lon": 88.5333,
    "elevationM": 1615,
    "averageSlopeDeg": 51,
    "geologyType": "Higher Himalayan Gneiss with Glacial Moraine",
    "historicalEventCount": 63,
    "population": 43709,
    "deocContact": "03592-234244"
  },
  {
    "id": "sk_gangtok",
    "name": "Gangtok (East Sikkim)",
    "nameHi": "गंगटोक (पूर्वी सिक्किम / एनएच-10)",
    "nameAs": "গেংটক (পূব ছিকিম / এনএইচ-১০)",
    "nameBn": "গ্যাংটক (পূর্ব সিকিম / এনএইচ-১০)",
    "nameMni": "গাংতোক (নোংপোক সিকিম)",
    "nameLus": "Gangtok (East Sikkim)",
    "nameKha": "Gangtok (East Sikkim)",
    "nameNe": "गान्तोक (पूर्वी सिक्किम / एनएच-১০)",
    "state": "Sikkim",
    "lat": 27.3389,
    "lon": 88.6065,
    "elevationM": 1650,
    "averageSlopeDeg": 44,
    "geologyType": "Daling Group Phyllites & Quartz-mica Schists",
    "historicalEventCount": 58,
    "population": 283583,
    "deocContact": "03592-284444"
  },
  {
    "id": "sk_gyalshing",
    "name": "Gyalshing (West Sikkim)",
    "nameHi": "ग्यालशिंग (पश्चिम सिक्किम)",
    "nameAs": "গ্যালছিং (পশ্চিম ছিকিম)",
    "nameBn": "গ্যালশিং (পশ্চিম সিকিম)",
    "nameMni": "গ্যালশিং (নোংচুপ সিকিম)",
    "nameLus": "Gyalshing (West Sikkim)",
    "nameKha": "Gyalshing (West Sikkim)",
    "nameNe": "ग्यालशिङ (पश्चिम सिक्किम)",
    "state": "Sikkim",
    "lat": 27.2833,
    "lon": 88.25,
    "elevationM": 2000,
    "averageSlopeDeg": 43,
    "geologyType": "Darjeeling Gneiss & Mica Schists",
    "historicalEventCount": 37,
    "population": 136435,
    "deocContact": "03595-250888"
  },
  {
    "id": "sk_namchi",
    "name": "Namchi (South Sikkim)",
    "nameHi": "नामची (दक्षिण सिक्किम)",
    "nameAs": "নামচি (দক্ষিণ ছিকিম)",
    "nameBn": "নামচি (দক্ষিণ সিকিম)",
    "nameMni": "নামচি (খা সিকিম)",
    "nameLus": "Namchi (South Sikkim)",
    "nameKha": "Namchi (South Sikkim)",
    "nameNe": "नाम्ची (दक्षिण सिक्किम)",
    "state": "Sikkim",
    "lat": 27.1667,
    "lon": 88.35,
    "elevationM": 1315,
    "averageSlopeDeg": 40,
    "geologyType": "Gondwana Sandstone & Overthrusted Schists",
    "historicalEventCount": 32,
    "population": 146850,
    "deocContact": "03595-254224"
  }
];
