import type { DistrictProfile, NerState } from './types';

export const NER_DISTRICTS: DistrictProfile[] = [
  // ASSAM
  {
    id: 'as_dima_hasao',
    name: 'Dima Hasao',
    nameHi: 'दीमा हसाओ',
    state: 'Assam',
    lat: 25.1834,
    lon: 93.0232,
    elevationM: 950,
    averageSlopeDeg: 34,
    geologyType: 'Tertiary Shale & Sandstone',
    historicalEventCount: 38,
    population: 214102,
    deocContact: '03673-236324',
  },
  {
    id: 'as_karbi_anglong',
    name: 'Karbi Anglong',
    nameHi: 'कार्बी आंगलोंग',
    state: 'Assam',
    lat: 26.1158,
    lon: 93.4243,
    elevationM: 680,
    averageSlopeDeg: 28,
    geologyType: 'Precambrian Metamorphics & Sedimentary',
    historicalEventCount: 19,
    population: 956313,
    deocContact: '03671-272555',
  },
  {
    id: 'as_kamrup_metro',
    name: 'Kamrup Metropolitan (Guwahati)',
    nameHi: 'कामरूप मेट्रोपॉलिटन (गुवाहाटी)',
    state: 'Assam',
    lat: 26.1445,
    lon: 91.7362,
    elevationM: 120,
    averageSlopeDeg: 24,
    geologyType: 'Gneissic Complex & Residual Soil Hills',
    historicalEventCount: 29,
    population: 1253938,
    deocContact: '0361-2733052',
  },
  {
    id: 'as_cachar',
    name: 'Cachar',
    nameHi: 'कछार',
    state: 'Assam',
    lat: 24.8333,
    lon: 92.8000,
    elevationM: 85,
    averageSlopeDeg: 22,
    geologyType: 'Surma Group Siltstone & Clay',
    historicalEventCount: 14,
    population: 1736617,
    deocContact: '03842-245840',
  },

  // MEGHALAYA
  {
    id: 'ml_east_khasi_hills',
    name: 'East Khasi Hills (Cherrapunji/Shillong)',
    nameHi: 'पूर्वी खासी हिल्स (चेरापूंजी/शिलांग)',
    state: 'Meghalaya',
    lat: 25.5788,
    lon: 91.8933,
    elevationM: 1496,
    averageSlopeDeg: 42,
    geologyType: 'Shillong Group Quartzites & Basalt Trap',
    historicalEventCount: 52,
    population: 825922,
    deocContact: '0364-2224140',
  },
  {
    id: 'ml_sw_khasi_hills',
    name: 'South West Khasi Hills (Mawsynram)',
    nameHi: 'दक्षिण पश्चिम खासी हिल्स (मासिनराम)',
    state: 'Meghalaya',
    lat: 25.3000,
    lon: 91.5833,
    elevationM: 1400,
    averageSlopeDeg: 39,
    geologyType: 'Limestone Scarp & Sandstone Plateau',
    historicalEventCount: 46,
    population: 110152,
    deocContact: '03656-285222',
  },
  {
    id: 'ml_ri_bhoi',
    name: 'Ri-Bhoi (NH-6 Corridor)',
    nameHi: 'री-भोई (एनएच-6 गलियारा)',
    state: 'Meghalaya',
    lat: 25.9000,
    lon: 91.8833,
    elevationM: 520,
    averageSlopeDeg: 31,
    geologyType: 'Granite Gneiss with Deep Saprolite',
    historicalEventCount: 31,
    population: 258840,
    deocContact: '03638-232223',
  },
  {
    id: 'ml_west_garo_hills',
    name: 'West Garo Hills (Tura)',
    nameHi: 'पश्चिम गारो हिल्स (तुरा)',
    state: 'Meghalaya',
    lat: 25.5167,
    lon: 90.2167,
    elevationM: 650,
    averageSlopeDeg: 33,
    geologyType: 'Archaeon Gneisses & Tertiary Sediments',
    historicalEventCount: 22,
    population: 643291,
    deocContact: '03651-223835',
  },

  // ARUNACHAL PRADESH
  {
    id: 'ar_papum_pare',
    name: 'Papum Pare (Itanagar)',
    nameHi: 'पापुम पारे (ईटानगर)',
    state: 'Arunachal Pradesh',
    lat: 27.1004,
    lon: 93.6166,
    elevationM: 750,
    averageSlopeDeg: 38,
    geologyType: 'Siwalik Fragile Sandstone & Silt',
    historicalEventCount: 36,
    population: 176573,
    deocContact: '0360-2212374',
  },
  {
    id: 'ar_tawang',
    name: 'Tawang',
    nameHi: 'तवांग',
    state: 'Arunachal Pradesh',
    lat: 27.5861,
    lon: 91.8594,
    elevationM: 3048,
    averageSlopeDeg: 46,
    geologyType: 'Higher Himalayan Crystalline Complex',
    historicalEventCount: 44,
    population: 49977,
    deocContact: '03794-222222',
  },
  {
    id: 'ar_west_kameng',
    name: 'West Kameng (Bomdila/Bhalukpong)',
    nameHi: 'पश्चिम कामेंग (बोमडिला)',
    state: 'Arunachal Pradesh',
    lat: 27.2645,
    lon: 92.4159,
    elevationM: 2217,
    averageSlopeDeg: 44,
    geologyType: 'Lesser Himalayan Schist & Phyllite',
    historicalEventCount: 41,
    population: 83936,
    deocContact: '03782-222008',
  },
  {
    id: 'ar_east_siang',
    name: 'East Siang (Pasighat)',
    nameHi: 'पूर्वी सियांग (पासीघाट)',
    state: 'Arunachal Pradesh',
    lat: 28.0667,
    lon: 95.3333,
    elevationM: 153,
    averageSlopeDeg: 32,
    geologyType: 'Sub-Himalayan Foreland Basin & Alluvium',
    historicalEventCount: 27,
    population: 99214,
    deocContact: '0368-2222225',
  },
  {
    id: 'ar_dibang_valley',
    name: 'Dibang Valley (Anini)',
    nameHi: 'दिबांग घाटी (अनिनी)',
    state: 'Arunachal Pradesh',
    lat: 28.7900,
    lon: 95.9000,
    elevationM: 1968,
    averageSlopeDeg: 48,
    geologyType: 'Mishmi Metamorphics & Fault Gaps',
    historicalEventCount: 35,
    population: 8004,
    deocContact: '03801-222221',
  },

  // NAGALAND
  {
    id: 'nl_kohima',
    name: 'Kohima (Dzukou / NH-29)',
    nameHi: 'कोहिमा (एनएच-29 गलियारा)',
    state: 'Nagaland',
    lat: 25.6701,
    lon: 94.1077,
    elevationM: 1444,
    averageSlopeDeg: 37,
    geologyType: 'Disang Group Mudstone & Unstable Clay',
    historicalEventCount: 47,
    population: 267988,
    deocContact: '0370-2290028',
  },
  {
    id: 'nl_mokokchung',
    name: 'Mokokchung',
    nameHi: 'मोकोकचुंग',
    state: 'Nagaland',
    lat: 26.3256,
    lon: 94.5295,
    elevationM: 1325,
    averageSlopeDeg: 34,
    geologyType: 'Barail Group Sandstone-Shale Flisch',
    historicalEventCount: 23,
    population: 194622,
    deocContact: '0369-2226222',
  },
  {
    id: 'nl_phek',
    name: 'Phek',
    nameHi: 'फेक',
    state: 'Nagaland',
    lat: 25.6560,
    lon: 94.4980,
    elevationM: 1524,
    averageSlopeDeg: 39,
    geologyType: 'Ophiolite Belt & High Weathered Clay',
    historicalEventCount: 28,
    population: 163418,
    deocContact: '03865-223030',
  },

  // MANIPUR
  {
    id: 'mn_noney',
    name: 'Noney (Tupul Railway Zone)',
    nameHi: 'नोने (टुपुल रेलवे जोन)',
    state: 'Manipur',
    lat: 24.8100,
    lon: 93.6000,
    elevationM: 480,
    averageSlopeDeg: 43,
    geologyType: 'Thrust-Faulted Disang Shale & Colluvium',
    historicalEventCount: 39,
    population: 38290,
    deocContact: '03874-222123',
  },
  {
    id: 'mn_kangpokpi',
    name: 'Kangpokpi (NH-2 Lifeline)',
    nameHi: 'कांगपोकपी (एनएच-2)',
    state: 'Manipur',
    lat: 25.1500,
    lon: 93.9700,
    elevationM: 990,
    averageSlopeDeg: 36,
    geologyType: 'Soft Laminated Siltstone with Overburden',
    historicalEventCount: 31,
    population: 193744,
    deocContact: '03871-222415',
  },
  {
    id: 'mn_tamenglong',
    name: 'Tamenglong',
    nameHi: 'तमेंगलॉन्ग',
    state: 'Manipur',
    lat: 24.9833,
    lon: 93.4833,
    elevationM: 1260,
    averageSlopeDeg: 41,
    geologyType: 'Barail Formation Escarpment Slopes',
    historicalEventCount: 34,
    population: 140651,
    deocContact: '03877-267210',
  },

  // MIZORAM
  {
    id: 'mz_aizawl',
    name: 'Aizawl (Ramhlun / Hunthar Slope)',
    nameHi: 'आइजोल (रामहलुन/हुन्थार)',
    state: 'Mizoram',
    lat: 23.7271,
    lon: 92.7176,
    elevationM: 1132,
    averageSlopeDeg: 45,
    geologyType: 'Bhuban Formation Alternating Silt & Sand',
    historicalEventCount: 49,
    population: 400309,
    deocContact: '0389-2325372',
  },
  {
    id: 'mz_lunglei',
    name: 'Lunglei',
    nameHi: 'लुंगलेई',
    state: 'Mizoram',
    lat: 22.8671,
    lon: 92.7651,
    elevationM: 1222,
    averageSlopeDeg: 38,
    geologyType: 'Tertiary Folded Strata & Weathered Regolith',
    historicalEventCount: 26,
    population: 161428,
    deocContact: '0372-2324200',
  },
  {
    id: 'mz_champhai',
    name: 'Champhai (Indo-Myanmar Fault Zone)',
    nameHi: 'चम्फाई (भारत-म्यांमार भ्रंश क्षेत्र)',
    state: 'Mizoram',
    lat: 23.4754,
    lon: 93.3283,
    elevationM: 1678,
    averageSlopeDeg: 35,
    geologyType: 'Fractured Sandstone & Tectonic Suture',
    historicalEventCount: 21,
    population: 125745,
    deocContact: '03831-235222',
  },

  // TRIPURA
  {
    id: 'tr_dhalai',
    name: 'Dhalai (Ambassa)',
    nameHi: 'धलाई (अम्बासा)',
    state: 'Tripura',
    lat: 23.9167,
    lon: 91.8333,
    elevationM: 115,
    averageSlopeDeg: 26,
    geologyType: 'Tipam Group Semi-Consolidated Sandstone',
    historicalEventCount: 16,
    population: 378230,
    deocContact: '03826-267231',
  },
  {
    id: 'tr_north_tripura',
    name: 'North Tripura (Dharmanagar)',
    nameHi: 'उत्तर त्रिपुरा (धर्मनगर)',
    state: 'Tripura',
    lat: 24.3833,
    lon: 92.1667,
    elevationM: 88,
    averageSlopeDeg: 24,
    geologyType: 'Dupitila Unconsolidated Clay Sand Beds',
    historicalEventCount: 12,
    population: 417441,
    deocContact: '03822-220202',
  },

  // SIKKIM
  {
    id: 'sk_mangan',
    name: 'Mangan (North Sikkim / Chungthang)',
    nameHi: 'मंगन (उत्तरी सिक्किम/चुंगथांग)',
    state: 'Sikkim',
    lat: 27.5167,
    lon: 88.5333,
    elevationM: 1310,
    averageSlopeDeg: 51,
    geologyType: 'Higher Himalayan Gneiss with Glacial Moraine',
    historicalEventCount: 63,
    population: 43709,
    deocContact: '03592-234244',
  },
  {
    id: 'sk_gangtok',
    name: 'Gangtok (East Sikkim / NH-10)',
    nameHi: 'गंगटोक (पूर्वी सिक्किम / एनएच-10)',
    state: 'Sikkim',
    lat: 27.3389,
    lon: 88.6065,
    elevationM: 1650,
    averageSlopeDeg: 44,
    geologyType: 'Daling Group Phyllites & Quartz-mica Schists',
    historicalEventCount: 58,
    population: 283583,
    deocContact: '03592-284444',
  },
  {
    id: 'sk_namchi',
    name: 'Namchi (South Sikkim)',
    nameHi: 'नामची (दक्षिण सिक्किम)',
    state: 'Sikkim',
    lat: 27.1667,
    lon: 88.3500,
    elevationM: 1315,
    averageSlopeDeg: 40,
    geologyType: 'Gondwana Sandstone & Overthrusted Schists',
    historicalEventCount: 32,
    population: 146850,
    deocContact: '03595-254224',
  },
  {
    id: 'sk_gyalshing',
    name: 'Gyalshing (West Sikkim)',
    nameHi: 'ग्यालशिंग (पश्चिम सिक्किम)',
    state: 'Sikkim',
    lat: 27.2833,
    lon: 88.2500,
    elevationM: 1540,
    averageSlopeDeg: 43,
    geologyType: 'Darjeeling Gneiss & Mica Schists',
    historicalEventCount: 37,
    population: 136435,
    deocContact: '03595-250888',
  },
];

export const NER_STATES: NerState[] = [
  'Assam',
  'Meghalaya',
  'Arunachal Pradesh',
  'Nagaland',
  'Manipur',
  'Mizoram',
  'Tripura',
  'Sikkim',
];
