import type { DistrictProfile, RiskScoreBreakdown, WeatherTelemetry, SoilTelemetry, SeismicTelemetry } from './types';
import { NER_DISTRICTS } from './ner-districts';
import { NER_HIGHWAY_ROUTES } from './highway-navigation';
import { NER_SAFE_SHELTERS } from './safe-shelters';
import { NER_RIVER_GAUGES } from './river-gauges';

export function generateFullSitRep(
  riskMap: Map<string, RiskScoreBreakdown>,
  weatherMap: Map<string, WeatherTelemetry>,
  soilMap: Map<string, SoilTelemetry>,
  seismicMap: Map<string, SeismicTelemetry>,
  selectedDistrictId: string
): string {
  const now = new Date();
  const dateStr = now.toUTCString();
  const activeCritical = NER_DISTRICTS.filter(d => riskMap.get(d.id)?.level === 'CRITICAL');
  const activeHigh = NER_DISTRICTS.filter(d => riskMap.get(d.id)?.level === 'HIGH');
  const activeMod = NER_DISTRICTS.filter(d => riskMap.get(d.id)?.level === 'MODERATE');

  const selectedDistrict = NER_DISTRICTS.find(d => d.id === selectedDistrictId) || NER_DISTRICTS[0];
  const selectedRisk = riskMap.get(selectedDistrict.id);
  const selectedWeather = weatherMap.get(selectedDistrict.id);

  let sitrep = `# NEXTSIGNAL / MDoNER SITUATION REPORT (SITREP)
**Document ID:** SITREP-NER-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getUTCDate()).padStart(2, '0')}-${Math.floor(1000 + Math.random() * 9000)}
**Generated:** ${dateStr}
**Classification:** OFFICIAL DISASTER MONITORING INTELLIGENCE

---

## 1. EXECUTIVE SUMMARY & THEATER OVERVIEW
- **Monitored Mountain Districts:** 28 Districts (Assam, Meghalaya, Sikkim, Arunachal Pradesh, Nagaland, Manipur, Mizoram, Tripura)
- **CRITICAL Alert Districts (Score ≥ 70):** ${activeCritical.length} (${activeCritical.map(d => d.name).join(', ') || 'None'})
- **HIGH Alert Districts (Score 55-69):** ${activeHigh.length} (${activeHigh.map(d => d.name).join(', ') || 'None'})
- **MODERATE Alert Districts (Score 40-54):** ${activeMod.length}
- **Active Focus Target:** ${selectedDistrict.name}, ${selectedDistrict.state} (Score: ${selectedRisk?.compositeScore || 0}/100 [${selectedRisk?.level || 'LOW'}])

---

## 2. ACTIVE CRITICAL GEOHAZARD HIGHLIGHTS
${activeCritical.map(d => {
  const r = riskMap.get(d.id);
  const w = weatherMap.get(d.id);
  const s = soilMap.get(d.id);
  return `### 🚨 ${d.name} (${d.state})
- **Composite Risk:** ${r?.compositeScore}/100 [CRITICAL]
- **Primary Trigger:** ${r?.dominantTrigger}
- **24h / 72h Rainfall:** ${w?.rainfall24hMm || 0}mm / ${w?.rainfall72hMm || 0}mm (Forecast: ${w?.rainfallForecast24hMm || 0}mm)
- **Soil Moisture:** ${s?.soilMoisturePct || 0}% (${s?.soilSaturationStatus})
- **DEOC Control Room:** ${d.deocContact}
`;
}).join('\n') || 'No districts currently under CRITICAL alert.'}

---

## 3. ARTERIAL HIGHWAY CORRIDORS & CHOKE-POINT STATUS
${NER_HIGHWAY_ROUTES.map(h => `
- **${h.name}:** Status: **${h.currentPassStatus}** | Vulnerability: **${h.overallVulnerability}**
  - Choke Points: ${h.steps.filter(s => s.status !== 'CLEAR').map(s => `${s.locationName} (${s.hazardType})`).join('; ') || 'All clear'}
  - Managing Authority: ${h.managingAuthority} (Helpline: ${h.emergencyControlRoom})
`).join('')}

---

## 4. HYDROLOGICAL GLOF & RIVER BASIN GAUGES
${NER_RIVER_GAUGES.map(g => `
- **${g.stationName} (${g.riverName}):** Current Level: **${g.currentLevelM}m** (${g.trend}) | Danger Mark: ${g.dangerLevelM}m | GLOF Risk: **${g.glofRisk}**
`).join('')}

---

## 5. DESIGNATED SAFE EVACUATION SHELTERS
- Total Geocoded Shelters: ${NER_SAFE_SHELTERS.length} Relief Centers
- Total Regional Shelter Capacity: ${NER_SAFE_SHELTERS.reduce((sum, s) => sum + s.capacityPersons, 0).toLocaleString()} Persons
- Key High-Capacity Centers:
${NER_SAFE_SHELTERS.slice(0, 5).map(s => `  - ${s.name}: ${s.capacityPersons} pax (${s.type}, Alt: ${s.elevationM}m MSL, Contact: ${s.contactNumber})`).join('\n')}

---

*Report automatically generated by NextSignal AI Early Warning & Landslide Risk Monitoring Engine.*
`;

  return sitrep;
}

export function downloadSitRepFile(
  riskMap: Map<string, RiskScoreBreakdown>,
  weatherMap: Map<string, WeatherTelemetry>,
  soilMap: Map<string, SoilTelemetry>,
  seismicMap: Map<string, SeismicTelemetry>,
  selectedDistrictId: string
) {
  const sitrepContent = generateFullSitRep(riskMap, weatherMap, soilMap, seismicMap, selectedDistrictId);
  const blob = new Blob([sitrepContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `NextSignal_SitRep_${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
